In [358]:
import pandas as pd

In [359]:
df=pd.read_excel("Energy Indicators.xls")

In [360]:
df=df[17:244]

In [361]:
df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
17,nan,Afghanistan,Afghanistan,321,10,78.66928
18,nan,Albania,Albania,102,35,100
19,nan,Algeria,Algeria,1959,51,0.55101
20,nan,American Samoa,American Samoa,...,...,0.641026
21,nan,Andorra,Andorra,9,121,88.69565

In [362]:
l=['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']

In [363]:
df.drop(["Unnamed: 1","Unnamed: 0"],axis=1,inplace=True)

In [364]:
df.columns=l

In [365]:
df.reset_index(drop=True,inplace=True)

In [366]:
import numpy as np

In [367]:
df.replace("...",np.NaN,inplace=True)

In [368]:
df.Country=df.Country.str.replace("\d+","")
df.Country=df.Country.str.replace("\s[(][A-Za-z]+(\s*[A-za-z]*){0,8}[)]","")

In [369]:
df["Country"]=df["Country"].replace(["Republic of Korea","United States of America","United Kingdom of Great Britain and Northern Ireland"
           ,"China, Hong Kong Special Administrative Region"],
          ["South Korea","United States","United Kingdom","Hong Kong"])

In [370]:
energy=df

In [371]:
df.head()
df.tail(20)

,Country,Energy Supply,Energy Supply per Capita,% Renewable
207,Turkey,"4,897.0",64.0,28.53669
208,Turkmenistan,"1,102.0",210.0,0.0
209,Turks and Caicos Islands,3.0,85.0,0.0
210,Tuvalu,nan,nan,0.0
211,Uganda,452.0,12.0,68.01818
212,Ukraine,"4,844.0",107.0,8.067312
213,United Arab Emirates,"2,710.0",300.0,0.0
214,United Kingdom,"7,920.0",124.0,10.60047
215,United Republic of Tanzania,994.0,20.0,31.07284
216,United States,"90,838.0",286.0,11.57098
217,United States Virgin Islands,nan,nan,0.0
218,Uruguay,196.0,58.0,71.60504
219,Uzbekistan,"1,798.0",62.0,21.32841
220,Vanuatu,3.0,10.0,14.70588
221,Venezuela,"2,871.0",95.0,67.83452
222,Viet Nam,"2,554.0",28.0,45.32152
223,Wallis and Futuna Islands,0.0,26.0,0.0
224,Yemen,344.0,13.0,0.0
225,Zambia,400.0,26.0,99.71467
226,Zimbabwe,480.0,32.0,52.53612

In [372]:
gf=pd.read_csv("world_bank.csv",header=4)

In [373]:
gf["Country Name"]=gf["Country Name"].replace(["Korea, Rep.","Iran, Islamic Rep.","Hong Kong SAR, China"],
           ["South Korea","Iran","Hong Kong"])

In [374]:
g=gf.set_index("Country Name")

In [375]:
GDP=gf

In [376]:
sf=pd.read_excel("scimagojr-3.xlsx")

In [377]:
sf=ScimEn[ScimEn["Rank"]<16]

In [378]:

sf.set_index("Country",inplace=True)

In [379]:
sf.shape

(15, 7)

In [380]:
g=GDP[["Country Name","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015",]]

In [381]:
g.set_index("Country Name",inplace=True)

In [382]:
e=energy.set_index("Country")

In [383]:
df=pd.merge(sf,e,left_index=True,right_index=True)

In [384]:
df=pd.merge(df,g,left_index=True,right_index=True)

In [350]:
df.shape

(15, 20)

In [351]:
df.count()

Rank                        15
Documents                   15
Citable documents           15
Citations                   15
Self-citations              15
Citations per document      15
H index                     15
Energy Supply               15
Energy Supply per Capita    15
% Renewable                 15
2006                        15
2007                        15
2008                        15
2009                        15
2010                        15
2011                        15
2012                        15
2013                        15
2014                        15
2015                        14
dtype: int64

In [385]:
df["Energy Supply"]=df["Energy Supply"]*1000000 
df.head()

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
China,1,127050,126767,597237,411683,4.7,138,"127,191,000,000.0",93.0,19.75491,"3,992,331,462,570.89","4,559,041,383,517.93","4,997,775,145,605.96","5,459,247,267,275.14","6,039,658,508,485.59","6,612,490,294,273.65","7,124,977,970,399.61","7,672,447,738,017.42","8,230,120,617,793.52","8,797,998,940,421.28"
United States,2,96661,94747,792274,265436,8.2,230,"90,838,000,000.0",286.0,11.57098,"14,792,303,791,800.0","15,055,395,304,800.0","15,011,490,541,400.0","14,594,842,181,900.0","14,964,372,000,000.0","15,204,019,634,600.0","15,542,161,722,300.0","15,773,666,098,800.0","16,156,618,476,000.0","16,548,573,278,300.0"
Japan,3,30504,30287,223024,61554,7.31,134,"18,984,000,000.0",149.0,10.23282,"5,496,541,517,363.31","5,617,035,943,770.73","5,558,526,873,313.82","5,251,308,399,909.32","5,498,717,815,809.77","5,473,738,114,222.05","5,569,101,602,926.18","5,644,658,523,313.42","5,642,884,448,582.19","5,669,563,143,140.97"
United Kingdom,4,20944,20357,206091,37874,9.84,139,"7,920,000,000.0",124.0,10.60047,"2,419,630,700,401.73","2,482,203,235,475.9","2,470,614,405,284.3","2,367,047,611,711.99","2,403,504,326,328.8","2,450,911,011,124.85","2,479,808,627,472.19","2,533,370,110,012.36","2,605,643,189,894.93","2,666,333,396,477.13"
Russian Federation,5,18534,18301,34266,12422,1.85,57,"30,709,000,000.0",214.0,17.28868,"1,385,792,607,182.58","1,504,071,117,741.3","1,583,004,071,092.11","1,459,199,142,720.26","1,524,917,468,442.01","1,589,942,641,764.29","1,645,875,899,596.27","1,666,934,123,163.16","1,678,708,855,070.86","1,616,148,858,033.77"

In [305]:
df.dtypes

Rank                          int64
Documents                     int64
Citable documents             int64
Citations                     int64
Self-citations                int64
Citations per document      float64
H index                       int64
Energy Supply               float64
Energy Supply per Capita    float64
% Renewable                 float64
2006                        float64
2007                        float64
2008                        float64
2009                        float64
2010                        float64
2011                        float64
2012                        float64
2013                        float64
2014                        float64
2015                        float64
Energy Supply               float64
dtype: object

In [73]:
avg=df[["2006","2007","2008","2009","2010","2011","2012","2013","2014","2015"]].mean(axis=1).rename("avgGDP")

In [74]:
avg.sort_values(ascending=False)

United States         1.536434e+13
China                 6.348609e+12
Japan                 5.542208e+12
Germany               3.493025e+12
France                2.681725e+12
United Kingdom        2.487907e+12
Brazil                2.189794e+12
Italy                 2.120175e+12
India                 1.769297e+12
Canada                1.660647e+12
Russian Federation    1.565459e+12
Spain                 1.418078e+12
Australia             1.164043e+12
South Korea           1.106715e+12
Iran                  4.441558e+11
Name: avgGDP, dtype: float64

In [75]:
avgGDP = df[['2006','2007','2008','2009','2010','2011','2012','2013','2014','2015']].mean(axis=1).rename('avgGDP').sort_values(ascending=False)

In [76]:
avgGDP

United States         1.536434e+13
China                 6.348609e+12
Japan                 5.542208e+12
Germany               3.493025e+12
France                2.681725e+12
United Kingdom        2.487907e+12
Brazil                2.189794e+12
Italy                 2.120175e+12
India                 1.769297e+12
Canada                1.660647e+12
Russian Federation    1.565459e+12
Spain                 1.418078e+12
Australia             1.164043e+12
South Korea           1.106715e+12
Iran                  4.441558e+11
Name: avgGDP, dtype: float64

In [82]:
avgGDP.index[5]

'United Kingdom'

In [89]:
df.loc[avgGDP.index[5]][["2006","2015"]]

TypeError: flex_wrapper() missing 1 required positional argument: 'other'

In [90]:
df.head()

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
China,1,127050,126767,597237,411683,4.70,138,127191.0,93.0,19.75491,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12
United States,2,96661,94747,792274,265436,8.20,230,90838.0,286.0,11.57098,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13
Japan,3,30504,30287,223024,61554,7.31,134,18984.0,149.0,10.23282,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12
United Kingdom,4,20944,20357,206091,37874,9.84,139,7920.0,124.0,10.60047,2.419631e+12,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12
Russian Federation,5,18534,18301,34266,12422,1.85,57,30709.0,214.0,17.28868,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12

In [91]:
df["Energy Supply per Capita"].mean()

157.6

In [94]:
d=df[(df["% Renewable"])==(df["% Renewable"].max())]

In [95]:
d

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Brazil,15,8668,8596,60702,14396,7.0,86,12149.0,59.0,69.64803,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12

In [121]:
d["% Renewable"].tolist()

[69.64803]

In [123]:
d.index.values

array(['Brazil'], dtype=object)

In [124]:
d=df

In [125]:
d["new"]=d["Self-citations"]/d["Citations"]

In [126]:
d.head()

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,new
China,1,127050,126767,597237,411683,4.70,138,127191.0,93.0,19.75491,...,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12,0.689313
United States,2,96661,94747,792274,265436,8.20,230,90838.0,286.0,11.57098,...,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13,0.335031
Japan,3,30504,30287,223024,61554,7.31,134,18984.0,149.0,10.23282,...,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12,0.275997
United Kingdom,4,20944,20357,206091,37874,9.84,139,7920.0,124.0,10.60047,...,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12,0.183773
Russian Federation,5,18534,18301,34266,12422,1.85,57,30709.0,214.0,17.28868,...,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12,0.362517

In [127]:
df.corr()

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,new
Rank,1.000000,-0.703849,-0.702179,-0.689219,-0.640129,0.335432,-0.589597,-0.656759,-0.253657,0.295288,...,-0.587375,-0.596649,-0.605260,-0.615397,-0.624305,-0.632670,-0.640750,-0.646377,-0.630748,-0.509328
Documents,-0.703849,1.000000,0.999943,0.924086,0.991635,-0.360302,0.617514,0.973529,0.108474,-0.166832,...,0.692532,0.714274,0.745377,0.763783,0.784191,0.799996,0.816652,0.830983,0.840711,0.816992
Citable documents,-0.702179,0.999943,1.000000,0.920451,0.992488,-0.362623,0.611284,0.974058,0.103424,-0.165754,...,0.685671,0.707633,0.739044,0.757710,0.778357,0.794362,0.811247,0.825754,0.835549,0.821345
Citations,-0.689219,0.924086,0.920451,1.000000,0.897606,-0.111725,0.854724,0.860706,0.279274,-0.149209,...,0.871278,0.883392,0.902614,0.911067,0.921480,0.929063,0.936861,0.944320,0.949564,0.561326
Self-citations,-0.640129,0.991635,0.992488,0.897606,1.000000,-0.314783,0.580556,0.968527,0.043799,-0.133179,...,0.624007,0.647486,0.682508,0.702651,0.725270,0.742572,0.761249,0.777643,0.790658,0.835941
Citations per document,0.335432,-0.360302,-0.362623,-0.111725,-0.314783,1.000000,0.306977,-0.467667,0.124916,0.244349,...,-0.113902,-0.128897,-0.141112,-0.156990,-0.170657,-0.182627,-0.193492,-0.199785,-0.254229,-0.665226
H index,-0.589597,0.617514,0.611284,0.854724,0.580556,0.306977,1.000000,0.505392,0.399212,-0.063636,...,0.845043,0.843794,0.845414,0.842112,0.839667,0.836923,0.834091,0.832627,0.826819,0.085396
Energy Supply,-0.656759,0.973529,0.974058,0.860706,0.968527,-0.467667,0.505392,1.000000,0.025135,-0.165830,...,0.623897,0.647656,0.682087,0.702541,0.725422,0.743307,0.761878,0.778224,0.789133,0.875874
Energy Supply per Capita,-0.253657,0.108474,0.103424,0.279274,0.043799,0.124916,0.399212,0.025135,1.000000,-0.093667,...,0.359593,0.350808,0.334140,0.320286,0.310022,0.303070,0.292056,0.283620,0.253759,-0.213530
% Renewable,0.295288,-0.166832,-0.165754,-0.149209,-0.133179,0.244349,-0.063636,-0.165830,-0.093667,1.000000,...,-0.175533,-0.172766,-0.172028,-0.171468,-0.170287,-0.171599,-0.171410,-0.173420,-0.242144,-0.157020
2006,-0.574161,0.668326,0.661228,0.857514,0.598147,-0.096636,0.845677,0.597789,0.370842,-0.174815,...,0.999412,0.997790,0.993533,0.989662,0.984263,0.979190,0.972729,0.966406,0.958125,0.239591
2007,-0.587375,0.692532,0.685671,0.871278,0.624007,-0.113902,0.845043,0.623897,0.359593,-0.175533,...,1.000000,0.999472,0.996755,0.993926,0.989651,0.985465,0.979976,0.974468,0.967276,0.270173
2008,-0.596649,0.714274,0.707633,0.883392,0.647486,-0.128897,0.843794,0.647656,0.350808,-0.172766,...,0.999472,1.000000,0.998764,0.996881,0.993696,0.990344,0.985765,0.981035,0.974811,0.297400
2009,-0.605260,0.745377,0.739044,0.902614,0.682508,-0.141112,0.845414,0.682087,0.334140,-0.172028,...,0.996755,0.998764,1.000000,0.999476,0.997895,0.995814,0.992653,0.989216,0.984645,0.335687
2010,-0.615397,0.763783,0.757710,0.911067,0.702651,-0.156990,0.842112,0.702541,0.320286,-0.171468,...,0.993926,0.996881,0.999476,1.000000,0.999396,0.998130,0.995877,0.993138,0.989408,0.361818
2011,-0.624305,0.784191,0.778357,0.921480,0.725270,-0.170657,0.839667,0.725422,0.310022,-0.170287,...,0.989651,0.993696,0.997895,0.999396,1.000000,0.999617,0.998342,0.996499,0.993770,0.388839
2012,-0.632670,0.799996,0.794362,0.929063,0.742572,-0.182627,0.836923,0.743307,0.303070,-0.171599,...,0.985465,0.990344,0.995814,0.998130,0.999617,1.000000,0.999546,0.998398,0.996415,0.410587
2013,-0.640750,0.816652,0.811247,0.936861,0.761249,-0.193492,0.834091,0.761878,0.292056,-0.171410,...,0.979976,0.985765,0.992653,0.995877,0.998342,0.999546,1.000000,0.999620,0.998443,0.433798
2014,-0.646377,0.830983,0.825754,0.944320,0.777643,-0.199785,0.832627,0.778224,0.283620,-0.173420,...,0.974468,0.981035,0.989216,0.993138,0.996499,0.998398,0.999620,1.000000,0.999599,0.453261
2015,-0.630748,0.840711,0.835549,0.949564,0.790658,-0.254229,0.826819,0.789133,0.253759,-0.242144,...,0.967276,0.974811,0.984645,0.989408,0.993770,0.996415,0.998443,0.999599,1.000000,0.512623
new,-0.509328,0.816992,0.821345,0.561326,0.835941,-0.665226,0.085396,0.875874,-0.213530,-0.157020,...,0.270173,0.297400,0.335687,0.361818,0.388839,0.410587,0.433798,0.453261,0.512623,1.000000

In [386]:
import copy 

d=copy.deepcopy(df)

d["pop"]=d["Energy Supply"]/d["Energy Supply per Capita"]
d["c/p"]=d["Citable documents"]/d["pop"]

In [139]:
import copy
a=[1,2,3,4,5,[1,2,3]]
b=copy.deepcopy(a)
b[5][0]="hey"

In [140]:
a

[1, 2, 3, 4, 5, [1, 2, 3]]

In [387]:
d.corr()

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,...,2008,2009,2010,2011,2012,2013,2014,2015,pop,c/p
Rank,1.0,-0.703849223011015,-0.7021790631917579,-0.6892191781826107,-0.6401290641665657,0.33543208262381674,-0.589597086892063,-0.6567585487872335,-0.25365721509909167,0.2952883448428432,...,-0.5966494868127336,-0.605260383224764,-0.6153965955053521,-0.6243045064879097,-0.6326698479419456,-0.6407495808241452,-0.6463770357730685,-0.6307478678321878,-0.38196791793404095,-0.1690300994937774
Documents,-0.703849223011015,1.0,0.9999427789765156,0.9240860368070853,0.9916351093336719,-0.3603018558031177,0.6175138890436894,0.9735291353567292,0.10847429987337982,-0.16683196102006806,...,0.7142735734783208,0.7453768601258179,0.763782799935802,0.7841912348050708,0.7999960534026384,0.816651921888253,0.8309831530299316,0.8407113623556943,0.6025666695713979,-0.056706539597474154
Citable documents,-0.7021790631917579,0.9999427789765156,1.0,0.9204507524543761,0.9924883298196092,-0.3626229015791103,0.6112839180716411,0.9740578654569277,0.10342386043436659,-0.1657544510939038,...,0.7076326754717135,0.7390444988451732,0.7577103846799811,0.7783567735351353,0.7943617470665377,0.8112474687771695,0.8257540662096592,0.8355489205351786,0.6064985217494554,-0.06077528398998886
Citations,-0.6892191781826107,0.9240860368070853,0.9204507524543761,1.0,0.8976057580112626,-0.11172493725414709,0.8547235720105979,0.8607057254559424,0.2792738621746086,-0.14920922684188928,...,0.8833915573886124,0.9026139275955102,0.9110667859905032,0.9214798438975801,0.9290630586496431,0.9368614014196144,0.9443198439658932,0.949564059434385,0.42518713647504347,0.15723838650346791
Self-citations,-0.6401290641665657,0.9916351093336719,0.9924883298196092,0.8976057580112626,1.0,-0.3147830875874586,0.5805560444727569,0.9685265944875203,0.04379852193965163,-0.13317932602637372,...,0.6474858010972783,0.6825079251856027,0.7026513280013504,0.7252703528459254,0.7425719490448903,0.7612493449481733,0.777642711945618,0.7906576844782127,0.643755809384437,-0.08751350994293872
Citations per document,0.33543208262381674,-0.3603018558031177,-0.3626229015791103,-0.11172493725414709,-0.3147830875874586,1.0,0.30697732016482665,-0.4676667945027681,0.12491577490120043,0.24434853014421604,...,-0.12889669300558215,-0.14111211924762765,-0.15698980306270494,-0.17065692784197523,-0.18262667460251025,-0.19349194807722173,-0.19978494970474722,-0.25422916796562334,-0.34875055544061573,0.5437945830083107
H index,-0.589597086892063,0.6175138890436894,0.6112839180716411,0.8547235720105979,0.5805560444727569,0.30697732016482665,1.0,0.5053915321648126,0.3992119758309377,-0.06363606088300072,...,0.843793756119206,0.8454135683464257,0.84211185681954,0.8396672832261768,0.8369225758497513,0.8340911618165928,0.8326265099564554,0.8268188244435547,0.15447289171552064,0.4613188460343189
Energy Supply,-0.6567585487872335,0.9735291353567292,0.9740578654569277,0.8607057254559424,0.9685265944875203,-0.4676667945027681,0.5053915321648126,1.0,0.025134525277055342,-0.1658296173312864,...,0.6476559281162487,0.6820872925548573,0.7025410040138687,0.725422190535045,0.7433069668886398,0.7618784629811914,0.7782235164182919,0.7891331145060613,0.7216515601049757,-0.2147441571006262
Energy Supply per Capita,-0.25365721509909167,0.10847429987337982,0.10342386043436659,0.2792738621746086,0.04379852193965163,0.12491577490120043,0.3992119758309377,0.025134525277055342,1.0,-0.09366703160314943,...,0.3508082776110067,0.3341397085860833,0.3202857679849876,0.310022216255534,0.3030699031287827,0.2920564256858626,0.2836199211944508,0.2537587512970807,-0.47259259166855294,0.7940010435442943
% Renewable,0.2952883448428432,-0.16683196102006806,-0.1657544510939038,-0.14920922684188928,-0.13317932602637372,0.24434853014421604,-0.06363606088300072,-0.1658296173312864,-0.09366703160314943,1.0,...,-0.17276647670981166,-0.17202835161487434,-0.17146838361791827,-0.1702869692813149,-0.1715988319005095,-0.17140992154877432,-0.1734203866367556,-0.24214442558163743,-0.09866919964122403,0.05543134509496897
2006,-0.5741612018979312,0.668326416709095,0.6612280377928198,0.8575141659445391,0.5981471449151796,-0.09663617426734508,0.8456772834959889,0.5977886524166511,0.37084192457714854,-0.1748151858948105,...,0.9977895766949645,0.993533460243169,0.9896619268589231,0.9842629698589089,0.9791900408332747,0.9727294771437476,0.9664064252745299,0.9581245134705477,0.1049981630982832,0.17221019792213743
2007,-0.5873752941535473,0.692531956008528,0.6856714591130871,0.8712781912386143,0.6240069906045511,-0.11390184501162712,0.8450430456698681,0.6238965321571787,0.3595933175067176,-0.17553268646903003,...,0.9994718472559323,0.9967553206630652,0.9939258254612549,0.9896511605174254,0.9854648179257215,0.9799761583650499,0.974468415702833,0.9672762299710438,0.1312571960733627,0.15807065615610247
2008,-0.5966494868127336,0.7142735734783208,0.7076326754717135,0.8833915573886124,0.6474858010972783,-0.12889669300558215,0.843793756119206,0.6476559281162487,0.3508082776110067,-0.17276647670981166,...,1.0,0.9987641562411952,0.99688114722988,0.9936961634107778,0.9903441026217094,0.9857645614413866,0.981035269756428,0.9748108943462965,0.15463126608186292,0.14600036009184328
2009,-0.605260383224764,0.7453768601258179,0.7390444988451732,0.9026139275955102,0.6825079251856027,-0.14111211924762765,0.8454135683464257,0.6820872925548573,0.3341397085860833,-0.17202835161487434,...,0.9987641562411952,1.0,0.9994755978114063,0.9978952164295326,0.9958142112439929,0.9926528546762639,0.9892164903806349,0.9846447050970758,0.19484272477014525,0.12886370353986817
2010,-0.6153965955053521,0.763782799935802,0.7577103846799811,0.9110667859905032,0.7026513280013504,-0.15698980306270494,0.84211185681954,0.7025410040138687,0.3202857679849876,-0.17146838361791827,...,0.99688114722988,0.9994755978114063,1.0,0.9993959485346228,0.9981300294552191,0.9958773733625328,0.9931383023323239,0.9894075111812647,0.22011605407670637,0.11379464635677743
2011,-0.6243045064879097,0.7841912348050708,0.7783567735351353,0.9214798438975801,0.7252703528459254,-0.17065692784197523,0.8396672832261768,0.725422190535045,0.310022216255534,-0.1702869692813149,...,0.9936961634107778,0.9978952164295326,0.9993959485346228,1.0,0.9996169063809917,0.9983424544862146,0.9964991714008009,0.993770227177608,0.24577484832755314,0.10147301110901095
2012,-0.6326698479419456,0.7999960534026384,0.7943617470665377,0.9290630586496431,0.7425719490448903,-0.18262667460251025,0.8369225758497513,0.7433069668886398,0.3030699031287827,-0.1715988319005095,...,0.9903441026217094,0.9958142112439929,0.9981300294552191,0.9996169063809917,1.0,0.9995459886341843,0.9983975434931122,0.9964148957650648,0.2670905167549763,0.09329337153536235
2013,-0.6407495808241452,0.816651921888253,0.8112474687771695,0.9368614014196144,0.7612493449481733,-0.19349194807722173,0.8340911618165928,0.7618784629811914,0.2920564256858626,-0.17140992154877432,...,0.9857645614413866,0.9926528546762639,0.9958773733625328,0.9983424544862146,0.9995459886341843,1.0,0.9996203124543396,0.9984425851189254,0.2907676022813852,0.0831250243938852
2014,-0.6463770357730685,0.8309831530299316,0.8257540662096592,0.9443198439658932,0.777642711945618,-0.19978494970474722,0.8326265099564554,0.7782235164182919,0.2836199211944508,-0.1734203866367556,...,0.981035269756428,0.9892164903806349,0.9931383023323239,0.9964991714008009,0.9983975434931122,0.9996203124543396,1.0,0.9995988942736795,0.31182831183012655,0.07535695688118409
2015,-0.6307478678321878,0.8407113623556943,0.8355489205351786,0.949564059434385,0.7906576844782127,-0.25422916796562334,0.8268188244435547,0.7891331145060613,0.2537587512970807,-0.24214442558163743,...,0.9748108943462965,0.9846447050970758,0.9894075111812647,0.993770227177608,0.9964148957650648,0.9984425851189254,0.9995988942736795,1.0,0.3166355403526269,0.026550174276969835
pop,-0.38196791793404095,0.6025666695713979,0.6064985217494554,0.42518713647504347,0.643755809384437,-0.34875055544061573,0.15447289171552064,0.7216515601049757,-0.47259259166855294,-0.09866919964122403,...,0.15463126608186292,0.19484272477014525,0.22011605407670637,0.24577484832755314,0.2670905167549763,0.2907676022813852,0.31182831183012655,0.3166355403526269,1.0,-0.5296539178693624
c/p,-0.1690300994937774,-0.056706539597474154,-0.06077528398998886,0.15723838650346791,-0.08751350994293872,0.5437945830083107,0.4613188460343189,-0.2147441571006262,0.7940010435442943,0.05543134509496897,...,0.14600036009184328,0.12886370353986817,0.11379464635677743,0.10147301110901095,0.09329337153536235,0.0831250243938852,0.07535695688118409,0.026550174276969835,-0.5296539178693624,1.0

In [169]:
df.head()

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
China,1,127050,126767,597237,411683,4.70,138,127191.0,93.0,19.75491,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12
United States,2,96661,94747,792274,265436,8.20,230,90838.0,286.0,11.57098,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13
Japan,3,30504,30287,223024,61554,7.31,134,18984.0,149.0,10.23282,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12
United Kingdom,4,20944,20357,206091,37874,9.84,139,7920.0,124.0,10.60047,2.419631e+12,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12
Russian Federation,5,18534,18301,34266,12422,1.85,57,30709.0,214.0,17.28868,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12

In [170]:
df["% Renewable"].median()

17.02028

In [171]:
a=df["% Renewable"]>df["% Renewable"].median()

In [175]:
a=a.astype(int)

In [176]:
a

China                 1
United States         0
Japan                 0
United Kingdom        0
Russian Federation    1
Canada                1
Germany               1
India                 0
France                0
South Korea           0
Italy                 1
Spain                 1
Iran                  0
Australia             0
Brazil                1
Name: % Renewable, dtype: int64

In [177]:
df.head()

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
China,1,127050,126767,597237,411683,4.70,138,127191.0,93.0,19.75491,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12
United States,2,96661,94747,792274,265436,8.20,230,90838.0,286.0,11.57098,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13
Japan,3,30504,30287,223024,61554,7.31,134,18984.0,149.0,10.23282,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12
United Kingdom,4,20944,20357,206091,37874,9.84,139,7920.0,124.0,10.60047,2.419631e+12,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12
Russian Federation,5,18534,18301,34266,12422,1.85,57,30709.0,214.0,17.28868,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12

In [207]:
ContinentDict  = {'China':'Asia', 
                  'United States':'North America', 
                  'Japan':'Asia', 
                  'United Kingdom':'Europe', 
                  'Russian Federation':'Europe', 
                  'Canada':'North America', 
                  'Germany':'Europe', 
                  'India':'Asia',
                  'France':'Europe', 
                  'South Korea':'Asia', 
                  'Italy':'Europe', 
                  'Spain':'Europe', 
                  'Iran':'Asia',
                  'Australia':'Australia', 
                  'Brazil':'South America'}
b=pd.Series(ContinentDict).rename("Continent")

In [197]:
b.head()

China                          Asia
United States         North America
Japan                          Asia
United Kingdom               Europe
Russian Federation           Europe
Name: Continent, dtype: object

In [186]:
b
d=copy.copy(df)

In [208]:
d=pd.concat([d,b],axis=1)

In [189]:
df.head()

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
China,1,127050,126767,597237,411683,4.70,138,127191.0,93.0,19.75491,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12
United States,2,96661,94747,792274,265436,8.20,230,90838.0,286.0,11.57098,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13
Japan,3,30504,30287,223024,61554,7.31,134,18984.0,149.0,10.23282,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12
United Kingdom,4,20944,20357,206091,37874,9.84,139,7920.0,124.0,10.60047,2.419631e+12,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12
Russian Federation,5,18534,18301,34266,12422,1.85,57,30709.0,214.0,17.28868,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12

In [190]:
d.head()

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,Continent
China,1,127050,126767,597237,411683,4.70,138,127191.0,93.0,19.75491,...,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12,Asia
United States,2,96661,94747,792274,265436,8.20,230,90838.0,286.0,11.57098,...,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13,North America
Japan,3,30504,30287,223024,61554,7.31,134,18984.0,149.0,10.23282,...,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12,Asia
United Kingdom,4,20944,20357,206091,37874,9.84,139,7920.0,124.0,10.60047,...,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12,Europe
Russian Federation,5,18534,18301,34266,12422,1.85,57,30709.0,214.0,17.28868,...,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12,Europe

In [221]:
d["pop"]=d["Energy Supply"]/d["Energy Supply per Capita"]

In [192]:
d.head()

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,...,2008,2009,2010,2011,2012,2013,2014,2015,Continent,pop
China,1,127050,126767,597237,411683,4.70,138,127191.0,93.0,19.75491,...,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12,Asia,1367.645161
United States,2,96661,94747,792274,265436,8.20,230,90838.0,286.0,11.57098,...,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13,North America,317.615385
Japan,3,30504,30287,223024,61554,7.31,134,18984.0,149.0,10.23282,...,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12,Asia,127.409396
United Kingdom,4,20944,20357,206091,37874,9.84,139,7920.0,124.0,10.60047,...,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12,Europe,63.870968
Russian Federation,5,18534,18301,34266,12422,1.85,57,30709.0,214.0,17.28868,...,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12,Europe,143.500000

In [195]:
d.groupby("Continent").pop.agg(["size","sum","mean","std"])

               size          sum        mean         std
Continent
Asia              5  2898.666387  579.733277  679.097888
Australia         1    23.316017   23.316017         NaN
Europe            6   457.929667   76.321611   34.647667
North America     2   352.855249  176.427625  199.669645
South America     1   205.915254  205.915254         NaN

In [202]:
d=df.copy()

In [204]:
d["br"]=pd.cut(d["% Renewable"],5,labels=[1,2,3,4,5])

In [205]:
d.head()

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,br
China,1,127050,126767,597237,411683,4.70,138,127191.0,93.0,19.75491,...,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12,2
United States,2,96661,94747,792274,265436,8.20,230,90838.0,286.0,11.57098,...,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13,1
Japan,3,30504,30287,223024,61554,7.31,134,18984.0,149.0,10.23282,...,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12,1
United Kingdom,4,20944,20357,206091,37874,9.84,139,7920.0,124.0,10.60047,...,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12,1
Russian Federation,5,18534,18301,34266,12422,1.85,57,30709.0,214.0,17.28868,...,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12,2

In [217]:
s=d.groupby(["Continent","br"]).size()

In [218]:
s=s[s>0]

In [219]:
s

Continent      br
Asia           1     4
               2     1
Australia      1     1
Europe         1     1
               2     3
               3     2
North America  1     1
               5     1
South America  5     1
dtype: int64

In [220]:
s.sort_values()

Continent      br
Asia           2     1
Australia      1     1
Europe         1     1
North America  1     1
               5     1
South America  5     1
Europe         3     2
               2     3
Asia           1     4
dtype: int64

In [222]:
d.head()

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,...,2009,2010,2011,2012,2013,2014,2015,br,Continent,pop
China,1,127050,126767,597237,411683,4.70,138,127191.0,93.0,19.75491,...,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12,2,Asia,1367.645161
United States,2,96661,94747,792274,265436,8.20,230,90838.0,286.0,11.57098,...,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13,1,North America,317.615385
Japan,3,30504,30287,223024,61554,7.31,134,18984.0,149.0,10.23282,...,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12,1,Asia,127.409396
United Kingdom,4,20944,20357,206091,37874,9.84,139,7920.0,124.0,10.60047,...,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12,1,Europe,63.870968
Russian Federation,5,18534,18301,34266,12422,1.85,57,30709.0,214.0,17.28868,...,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12,2,Europe,143.500000

In [322]:
x = 3000000000000000000
y = 300000000
print("\nOriginal Number: ", x)
print("Formatted Number with comma separator: "+"{:,}".format(x));
print("Original Number: ", y)
print("Formatted Number with comma separator: "+"{:,}".format(y));
print()

Original Number:  3000000000000000000
Formatted Number with comma separator: 3,000,000,000,000,000,000
Original Number:  300000000
Formatted Number with comma separator: 300,000,000

In [354]:
pd.options.display.float_format = '{:,}'.format
d.head()

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,...,2008,2009,2010,2011,2012,2013,2014,2015,pop,c/p
China,1,127050,126767,597237,411683,4.7,138,"127,191,000,000.0",93.0,19.75491,...,"4,997,775,145,605.96","5,459,247,267,275.14","6,039,658,508,485.59","6,612,490,294,273.65","7,124,977,970,399.61","7,672,447,738,017.42","8,230,120,617,793.52","8,797,998,940,421.28","1,367,645,161.2903225",9.268997806448569e-05
United States,2,96661,94747,792274,265436,8.2,230,"90,838,000,000.0",286.0,11.57098,...,"15,011,490,541,400.0","14,594,842,181,900.0","14,964,372,000,000.0","15,204,019,634,600.0","15,542,161,722,300.0","15,773,666,098,800.0","16,156,618,476,000.0","16,548,573,278,300.0","317,615,384.61538464",0.0002983073383385808
Japan,3,30504,30287,223024,61554,7.31,134,"18,984,000,000.0",149.0,10.23282,...,"5,558,526,873,313.82","5,251,308,399,909.32","5,498,717,815,809.77","5,473,738,114,222.05","5,569,101,602,926.18","5,644,658,523,313.42","5,642,884,448,582.19","5,669,563,143,140.97","127,409,395.97315437",0.00023771402233459756
United Kingdom,4,20944,20357,206091,37874,9.84,139,"7,920,000,000.0",124.0,10.60047,...,"2,470,614,405,284.3","2,367,047,611,711.99","2,403,504,326,328.8","2,450,911,011,124.85","2,479,808,627,472.19","2,533,370,110,012.36","2,605,643,189,894.93","2,666,333,396,477.13","63,870,967.741935484",0.0003187207070707071
Russian Federation,5,18534,18301,34266,12422,1.85,57,"30,709,000,000.0",214.0,17.28868,...,"1,583,004,071,092.11","1,459,199,142,720.26","1,524,917,468,442.01","1,589,942,641,764.29","1,645,875,899,596.27","1,666,934,123,163.16","1,678,708,855,070.86","1,616,148,858,033.77","143,500,000.0",0.00012753310104529617

In [355]:
s=d["Energy Supply"]

In [357]:
s.dtypes

dtype('float64')

In [389]:
d = d.applymap("{:,}".format)

In [390]:
d

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,...,2008,2009,2010,2011,2012,2013,2014,2015,pop,c/p
China,1,"127,050","126,767","597,237","411,683",4.7,138,"127,191,000,000.0",93.0,19.75491,...,"4,997,775,145,605.96","5,459,247,267,275.14","6,039,658,508,485.59","6,612,490,294,273.65","7,124,977,970,399.61","7,672,447,738,017.42","8,230,120,617,793.52","8,797,998,940,421.28","1,367,645,161.2903225",9.268997806448569e-05
United States,2,"96,661","94,747","792,274","265,436",8.2,230,"90,838,000,000.0",286.0,11.57098,...,"15,011,490,541,400.0","14,594,842,181,900.0","14,964,372,000,000.0","15,204,019,634,600.0","15,542,161,722,300.0","15,773,666,098,800.0","16,156,618,476,000.0","16,548,573,278,300.0","317,615,384.61538464",0.0002983073383385808
Japan,3,"30,504","30,287","223,024","61,554",7.31,134,"18,984,000,000.0",149.0,10.23282,...,"5,558,526,873,313.82","5,251,308,399,909.32","5,498,717,815,809.77","5,473,738,114,222.05","5,569,101,602,926.18","5,644,658,523,313.42","5,642,884,448,582.19","5,669,563,143,140.97","127,409,395.97315437",0.00023771402233459756
United Kingdom,4,"20,944","20,357","206,091","37,874",9.84,139,"7,920,000,000.0",124.0,10.60047,...,"2,470,614,405,284.3","2,367,047,611,711.99","2,403,504,326,328.8","2,450,911,011,124.85","2,479,808,627,472.19","2,533,370,110,012.36","2,605,643,189,894.93","2,666,333,396,477.13","63,870,967.741935484",0.0003187207070707071
Russian Federation,5,"18,534","18,301","34,266","12,422",1.85,57,"30,709,000,000.0",214.0,17.28868,...,"1,583,004,071,092.11","1,459,199,142,720.26","1,524,917,468,442.01","1,589,942,641,764.29","1,645,875,899,596.27","1,666,934,123,163.16","1,678,708,855,070.86","1,616,148,858,033.77","143,500,000.0",0.00012753310104529617
Canada,6,"17,899","17,620","215,003","40,930",12.01,149,"10,431,000,000.0",296.0,61.94543,...,"1,612,713,061,250.24","1,565,144,676,082.31","1,613,406,134,731.12","1,664,086,754,804.89","1,693,132,927,878.08","1,730,687,770,724.13","1,773,485,821,199.77","1,792,608,764,608.81","35,239,864.86486486",0.0005000019173617103
Germany,7,"17,027","16,831","140,566","27,426",8.26,126,"13,261,000,000.0",165.0,17.90153,...,"3,478,809,377,483.44","3,283,339,933,774.83","3,417,298,013,245.03","3,542,371,125,827.81","3,556,723,774,834.44","3,567,317,390,728.48","3,624,386,278,145.7","3,685,555,907,284.77","80,369,696.96969697",0.0002094197270190785
India,8,"15,005","14,841","128,763","37,209",8.58,115,"33,195,000,000.0",26.0,14.96908,...,"1,428,360,609,657.8","1,549,482,541,544.7","1,708,458,876,829.92","1,821,872,415,623.62","1,924,235,460,945.25","2,051,981,849,791.69","2,200,616,575,310.97","2,367,206,118,959.06","1,276,730,769.2307692",1.1624220515137823e-05
France,9,"13,153","12,973","130,632","28,601",9.93,114,"10,597,000,000.0",166.0,17.02028,...,"2,674,637,086,092.71","2,595,966,887,417.22","2,646,994,701,986.75","2,702,031,788,079.47","2,706,968,211,920.53","2,722,566,887,417.22","2,729,631,788,079.47","2,761,185,430,463.58","63,837,349.39759036",0.00020321959045012738
South Korea,10,"11,983","11,923","114,675","22,595",9.57,104,"11,007,000,000.0",221.0,2.279353,...,"1,020,509,638,539.71","1,027,729,932,849.17","1,094,499,338,702.72","1,134,795,571,930.64","1,160,809,426,196.79","1,194,429,021,591.57","1,234,340,240,503.49","1,266,580,410,309.11","49,805,429.864253394",0.00023939156900154446
Italy,11,"10,964","10,794","111,850","26,661",10.2,106,"6,530,000,000.0",109.0,33.66723,...,"2,211,154,176,556.29","2,089,937,511,523.18","2,125,184,794,172.19","2,137,439,133,774.83","2,077,184,315,761.59","2,040,871,178,145.7","2,033,867,707,549.67","2,049,315,603,576.16","59,908,256.880733944",0.00018017549770290965
Spain,12,"9,428","9,330","123,336","23,964",13.08,115,"4,923,000,000.0",106.0,37.96859,...,"1,484,529,801,324.5","1,431,475,496,688.74","1,431,672,847,682.12","1,417,354,966,887.42","1,380,215,894,039.73","1,357,139,072,847.68","1,375,605,298,013.24","1,419,821,192,052.98","46,443,396.2264151",0.00020088970140158438
Iran,13,"8,896","8,819","57,470","19,125",6.46,72,"9,172,000,000.0",119.0,5.707721,...,"428,990,857,822.095","438,920,754,763.986","467,790,215,915.476","485,330,901,134.448","453,256,899,727.83203","444,592,553,889.771","463,902,735,245.89",nan,"77,075,630.25210084",0.00011442008286088094
Australia,14,"8,831","8,725","90,765","15,606",10.28,107,"5,386,000,000.0",231.0,11.81081,...,"1,099,643,871,866.03","1,119,653,852,349.08","1,142,250,506,474.06","1,169,431,057,881.91","1,211,913,217,353.49","1,241,484,494,446.53","1,272,519,759,757.29","1,301,251,030,445.66","23,316,017.316017315",0.00037420627552914965
Brazil,15,"8,668","8,596","60,702","14,396",7.0,86,"12,149,000,000.0",59.0,69.64803,...,"2,056,809,174,052.93","2,054,214,562,458.19","2,208,872,214,643.02","2,295,244,758,549.53","2,339,209,222,185.09","2,409,739,667,075.82","2,412,230,647,720.45","2,319,423,390,494.13","205,915,254.23728815",4.1745328833648856e-05

In [391]:
df.dtypes

Rank                          int64
Documents                     int64
Citable documents             int64
Citations                     int64
Self-citations                int64
Citations per document      float64
H index                       int64
Energy Supply               float64
Energy Supply per Capita    float64
% Renewable                 float64
2006                        float64
2007                        float64
2008                        float64
2009                        float64
2010                        float64
2011                        float64
2012                        float64
2013                        float64
2014                        float64
2015                        float64
dtype: object